### ISSUE TITLE
Install pyheif Problems encountered

### ISSUE THREAD

**Issue by riitei** [david-poirier-csn/pyheif#12]
Hello

Computer environment
mac os 10.15.3
python3.8.1
pip 20.0.2
libheif 1.6.2

Installation execution
pip install git + https: //github.com/david-poirier-csn/pyheif.git

Encountered a problem and asked for your assistance

The installation displays the error message as follows:

 ERROR: Command errored out with exit status 1:
     command: / Users / XX / venv / bin / python -c 'import sys, setuptools, tokenize; sys.argv [0] =' "'"' / private / var / folders / bl / _44936q503n4ys2h1x0vlhv00000gn / T / pip-req -build-sof6win7 / setup.py '"'" '; __file __ =' "'"' / private / var / folders / bl / _44936q503n4ys2h1x0vlhv00000gn / T / pip-req-build-sof6win7 / setup.py '"'" '' ; f = getattr (tokenize, '"'" 'open' "'"', open) (__ file __); code = f.read (). replace ('"'" '\ r \ n' "'"', '"'" '\ n' "'"'); f.close (); exec (compile (code, __file__, '"'" 'exec' "'"')) 'egg_info --egg-base / private / var / folders / bl / _44936q503n4ys2h1x0vlhv00000gn / T / pip-req-build-sof6win7 / pip-egg-info
         cwd: / private / var / folders / bl / _44936q503n4ys2h1x0vlhv00000gn / T / pip-req-build-sof6win7 /
    Complete output (45 lines):
    WARNING: The wheel package is not available.
    WARNING: The wheel package is not available.
      ERROR: Command errored out with exit status 1:
       command: / Users / XXX / venv / bin / python -u -c 'import sys, setuptools, tokenize; sys.argv [0] =' "'"' / private / var / folders / bl / _44936q503n4ys2h1x0vlhv00000gn / T / pip -wheel-0oj_inl2 / pycparser / setup.py '"'" '; __file __ =' "'"' / private / var / folders / bl / _44936q503n4ys2h1x0vlhv00000gn / T / pip-wheel-0oj_inl2 / pycparser / setup.py '"' ' "'; f = getattr (tokenize,'" '"' open '"' "', open) (__ file __); code = f.read (). replace ('" '"' \ r \ n '"' " ',' "'"' \ n '"'" '); f.close (); exec (compile (code, __file__,' "'"' exec '"'" '))' bdist_wheel -d / private / var / folders / bl / _44936q503n4ys2h1x0vlhv00000gn / T / pip-wheel-k3mivdut
           cwd: / private / var / folders / bl / _44936q503n4ys2h1x0vlhv00000gn / T / pip-wheel-0oj_inl2 / pycparser /
      Complete output (6 lines):
      usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
         or: setup.py --help [cmd1 cmd2 ...]
         or: setup.py --help-commands
         or: setup.py cmd --help
    
      error: invalid command 'bdist_wheel'
      ----------------------------------------
      ERROR: Failed building wheel for pycparser
    ERROR: Failed to build one or more wheels
    Traceback (most recent call last):
      File "/Users/XXXXX/venv/lib/python3.8/site-packages/setuptools/installer.py", line 128, in fetch_build_egg
        subprocess.check_call (cmd)
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 364, in check_call
        raise CalledProcessError (retcode, cmd)
    subprocess.CalledProcessError: Command '[' / Users / XXX / venv / bin / python ',' -m ',' pip ',' --disable-pip-version-check ',' wheel ',' --no- deps ',' -w ',' / var / folders / bl / _44936q503n4ys2h1x0vlhv00000gn / T / tmpw7rslhko ',' --quiet ',' pycparser ']' returned non-zero exit status 1.
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/bl/_44936q503n4ys2h1x0vlhv00000gn/T/pip-req-build-sof6win7/setup.py", line 6, in <module>
        setup (
      File "/Users/XXXXX/venv/lib/python3.8/site-packages/setuptools/__init__.py", line 143, in setup
        _install_setup_requires (attrs)
      File "/Users/XXXXX/venv/lib/python3.8/site-packages/setuptools/__init__.py", line 138, in _install_setup_requires
        dist.fetch_build_eggs (dist.setup_requires)
      File "/Users/XXXX/venv/lib/python3.8/site-packages/setuptools/dist.py", line 718, in fetch_build_eggs
        resolved_dists = pkg_resources.working_set.resolve (
      File "/Users/XXX/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 781, in resolve
        dist = best [req.key] = env.best_match (
      File "/Users/XXX/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1066, in best_match
        return self.obtain (req, installer)
      File "/Users/XXX/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1078, in obtain
        return installer (requirement)
      File "/Users/XXX/venv/lib/python3.8/site-packages/setuptools/dist.py", line 777, in fetch_build_egg
        return fetch_build_egg (self, req)
      File "/Users/XXXXX/venv/lib/python3.8/site-packages/setuptools/installer.py", line 130, in fetch_build_egg
        raise DistutilsError (str (e))
    distutils.errors.DistutilsError: Command '[' / Users / XXX / venv / bin / python ',' -m ',' pip ',' --disable-pip-version-check ',' wheel ','- no-deps ',' -w ',' / var / folders / bl / _44936q503n4ys2h1x0vlhv00000gn / T / tmpw7rslhko ',' --quiet ',' pycparser ']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

Current query
Solve the article (https://zhuanlan.zhihu.com/p/89858202
 ) Yes reinstall the pip suite, the problem is not resolved

How to solve this problem

Thank you

**Comment by david-poirier-csn** [comment]
try executing `pip install wheel` first
