### ISSUE TITLE
Error in import

### ISSUE THREAD

**Issue by shuhilya** [david-poirier-csn/pyheif#19]
import pyheif
  File "/usr/local/lib/python3.6/dist-packages/pyheif/__init__.py", line 1, in <module>
    from .reader import read_heif
  File "/usr/local/lib/python3.6/dist-packages/pyheif/reader.py", line 1, in <module>
    from _libheif_cffi import ffi, lib
ImportError: /usr/local/lib/python3.6/dist-packages/_libheif_cffi.abi3.so: undefined symbol: heif_image_handle_get_raw_color_profile

**Comment by david-poirier-csn** [comment]
Probably due to an old version of `libheif`. Try updating or building from source if no update available.

**Comment by panosangelopoulos** [comment]
Are you using the new Apple `M1` processor?

I'm facing the same issue under `M1`.

**Comment by carlosost** [comment]
Same issue here an no idea how to solve it. I am using an Ubuntu Docker image on a Mac M1.
I could at least compile using:
```
RUN set -ex \
    && mkdir build-deps \
    && cd /build-deps \
    && LIBHEIF_VERSION="1.12.0" \
    && wget https://github.com/strukturag/libheif/releases/download/v${LIBHEIF_VERSION}/libheif-${LIBHEIF_VERSION}.tar.gz \
    && tar xvf libheif-${LIBHEIF_VERSION}.tar.gz \
    && cd libheif-${LIBHEIF_VERSION} \
    && ./configure --prefix /usr \
    && make -j4 \
    && make install \
    && ldconfig
```

But now I am getting the same runtime error.
