### ISSUE TITLE
Readme has wrong lib name

### ISSUE THREAD

**Issue by azin634** [david-poirier-csn/pyheif#9]
I think the library is called libx265. Since x265 is the codec.

**Comment by david-poirier-csn** [comment]
The codec is actually HEVC/H.265, the encoder is called x265

**Comment by azin634** [comment]
Maybe I missed it but I couldn't find a package in apt-get called x265-dev. Found libx265-dev instead.
https://github.com/david-poirier-csn/pyheif/blame/master/README.md#L15
